# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Bbcode

# Model Form Field configuration
form: @/plugins/shahiemseymor/bbcode/models/emoticons/fields.yaml

# Model Class name
modelClass: ShahiemSeymor\Bbcode\Models\Emoticon

# Default redirect location
defaultRedirect: shahiemseymor/bbcode/emoticons

# Create page
create:
    title: Create Bbcode
    redirect: shahiemseymor/bbcode/emoticons/update/:id
    redirectClose: shahiemseymor/bbcode/emoticons

# Update page
update:
    title: Edit Bbcode
    redirect: shahiemseymor/bbcode/emoticons
    redirectClose: shahiemseymor/bbcode/emoticons

# Preview page
preview:
    title: Preview Bbcode